# Generated by Django 3.2.9 on 2021-11-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_customers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features')),
                ('icon', models.FileField(upload_to='features')),
                ('icon_background', models.CharField(max_length=25)),
                ('title', models.ImageField(upload_to='features')),
                ('description', models.ImageField(upload_to='features')),
                ('testimonial_description', models.TextField(max_length=255)),
                ('testimonial_author', models.CharField(max_length=255)),
                ('author_designation', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(upload_to='features')),
            ],
        ),
    ]
