# Generated by Django 3.2.9 on 2021-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20211117_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('image', models.ImageField(upload_to='reviews')),
                ('play', models.ImageField(upload_to='reviews')),
                ('logo', models.ImageField(upload_to='reviews/logo')),
            ],
        ),
    ]
