# Generated by Django 3.2.9 on 2021-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='logo',
            field=models.FileField(upload_to='reviews/logo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='play',
            field=models.FileField(upload_to='reviews'),
        ),
    ]
