# Generated by Django 3.2.9 on 2021-11-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='testimonials\\logo'),
        ),
    ]
