# Generated by Django 3.2.9 on 2021-11-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20211118_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketing')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
