# Generated by Django 3.2.9 on 2021-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.FileField(upload_to='marketing'),
        ),
    ]
