# Generated by Django 3.2.9 on 2021-11-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_marketing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='produc')),
                ('title', models.CharField(max_length=155)),
                ('logo', models.FileField(upload_to='product/logo')),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
