# Generated by Django 3.2.9 on 2021-11-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_product_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_bg_color',
            field=models.CharField(default='#fff', max_length=10),
        ),
    ]
