# Generated by Django 3.2.9 on 2021-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_blog_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('company_size', models.CharField(choices=[('1', '1-10'), ('2', '11-50'), ('3', '51-200'), ('4', '201-500')], max_length=128)),
                ('industry', models.CharField(choices=[('agriculture', 'Agriculture'), ('banking_&_finance', 'Banking & Finance'), ('business_services_&_software', 'Business Services & Software')], max_length=128)),
                ('jobe_role', models.CharField(choices=[('c_suite', 'C-Suite'), ('vp', 'VP')], max_length=128)),
                ('country', models.CharField(choices=[('united_states', 'United States'), ('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria'), ('american_samoa', 'American Samoa')], max_length=128)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
