# Generated by Django 3.2.9 on 2021-11-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='white_image',
            field=models.FileField(blank=True, null=True, upload_to='customers'),
        ),
    ]
