# Generated by Django 3.2.9 on 2021-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_customers_white_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.FileField(default='a', upload_to='product/hero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='studio', max_length=155),
            preserve_default=False,
        ),
    ]
